all : rapport

rapport :
		pdflatex "Projet Math.tex">/dev/null  && pdflatex "Projet Math.tex">/dev/null  

clean :
	rm -f ./*.aux
	rm -f ./*.log
	rm -f ./*.out
	rm -f ./*.pdf
	rm -f ./*.synctex.gz
	rm -f ./*.toc
