all : rapport

rapport :
		pdflatex SoutenancePRMA.tex>/dev/null  && pdflatex SoutenancePRMA.tex>/dev/null  

clean :
	rm -f ./*.aux
	rm -f ./*.log
	rm -f ./*.out
	rm -f ./*.pdf
	rm -f ./*.synctex.gz
	rm -f ./*.toc
	rm -f ./*.snm
	rm -f ./*.nav
